title: "Qianqian Tong"
subtitle: ""
name: "Qianqian Tong"
description: "PhD student in Transportation Engineering at UT Austin."
url: "https://qianntong.github.io"
baseurl: ""

remote_theme: "mmistakes/minimal-mistakes@4.27.3"

plugins:
  - jekyll-include-cache

custom_css:
  - /assets/css/custom.css

author:
  name: "Qianqian Tong"
  avatar: "/assets/images/profile.jpeg"
  affiliation: "PhD Student, Transportation Engineering, UT Austin"
  email: "qianqian_tong@utexas.edu"

  links:
  - label: "Personal Website"
    icon: "fas fa-globe"
    url: "https://qianntong.github.io/"

  - label: "TRAIN Lab"
    icon: "fas fa-university"
    url: "https://sites.utexas.edu/train/team/"

  - label: "ORCID"
    icon: "ai ai-orcid"
    url: "https://orcid.org/0000-0002-4015-8721"

  - label: "LinkedIn"
    icon: "fab fa-linkedin"
    url: "https://www.linkedin.com/in/tongqianqian/"
  

navigation:
  main:
    - title: "About"
      url: /
    - title: "Research"
      url: /research/
    - title: "Blog"
      url: /blog/
    - title: "CV"
      url: /cv/

include:
  - _pages

defaults:
  - scope:
      path: ""
    values:
      layout: single
      author_profile: true

breadcrumbs: false
search: false

collections:
  posts:
    output: true
    permalink: /blog/:title/

category_archive:
  type: disabled

tag_archive:
  type: disabled
