title: "Qianqian Tong"
subtitle: ""
name: "Qianqian Tong"
description: "PhD student in Civil Engineering at UT Austin. Research on intermodal terminals, simulation, and optimization."
url: "https://qianntong.github.io"
baseurl: ""

remote_theme: "mmistakes/minimal-mistakes@4.27.3"

plugins:
  - jekyll-include-cache

custom_css:
  - /assets/css/custom.css

author:
  name: "Qianqian Tong"
  avatar: "/assets/images/profile.jpeg"
  affiliation: "PhD Student, Civil Engineering, UT Austin"
  email: "qianqian_tong@utexas.edu"

navigation:
  main:
    - title: "About"
      url: /
    - title: "Research"
      url: /research/
    - title: "Blog"
      url: /blog/
    - title: "CV"
      url: /cv/

include:
  - _pages

defaults:
  - scope:
      path: ""
    values:
      layout: single
      author_profile: true

breadcrumbs: false
search: false

collections:
  posts:
    output: true
    permalink: /blog/:title/

category_archive:
  type: disabled

tag_archive:
  type: disabled
